import cv2
import pytesseract
import requests
import re
import numpy as np
import imutils
import random
import os
import time
from utils import *
from authenticate import scrape_mkm_prices

def order_points(pts):
    """
    Sorts the 4 corners of a detected rectangle to ensure consistent perspective warping.
    
    Args:
        pts (numpy.ndarray): An array of 4 points representing the corners of the detected card.
        
    Returns:
        numpy.ndarray: An array of the 4 points ordered consistently as: 
                       [top-left, top-right, bottom-right, bottom-left].
    """
    rect = np.zeros((4, 2), dtype="float32")
    s = pts.sum(axis=1)
    rect[0] = pts[np.argmin(s)]
    rect[2] = pts[np.argmax(s)]

    diff = np.diff(pts, axis=1)
    rect[1] = pts[np.argmin(diff)]
    rect[3] = pts[np.argmax(diff)]
    
    return rect

def extract_card_from_background(image_path): 
    """
    Finds a Magic card on a background and warps it into a clean, flat 2D rectangle.
    
    Args:
        image_path (str): The file path to the local webcam photo.
        
    Returns:
        numpy.ndarray | None: The flattened image of the card. Returns None if 
                              the card edges could not be detected.
    """
    img = cv2.imread(image_path)
    if img is None:
        log("ERROR", "OpenCV failed to load the image.")
        return None

    ratio = img.shape[0] / 800.0
    orig = img.copy()
    img_resized = cv2.resize(img, (int(img.shape[1] / ratio), 800))

    gray = cv2.cvtColor(img_resized, cv2.COLOR_BGR2GRAY)
    card = None
    best_contour = None

    modes = ["light_bg", "dark_bg"]

    for mode in modes:
        log("INFO", f"Trying extraction mode: {mode}...")
        
        if mode == "light_bg":
            # Black border on white table
            blurred = cv2.bilateralFilter(gray, FILTER[0], FILTER[1], FILTER[2])
            _, processed = cv2.threshold(blurred, THRESHOLD[0], THRESHOLD[1], 0)
            edges = imutils.auto_canny(processed)
            
        elif mode == "dark_bg":
            # black border on dark table.
            clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
            contrast_boosted = clahe.apply(gray)
            blurred = cv2.bilateralFilter(contrast_boosted, FILTER[0], FILTER[1], FILTER[2])
            edges = imutils.auto_canny(blurred)
            kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
            edges = cv2.dilate(edges, kernel, iterations=1)

        contours, _ = cv2.findContours(edges.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
        cnts = [c for c in contours if cv2.contourArea(c) >= MIN_CARD_AREA]

        if cnts:
            cnts = sorted(cnts, key=cv2.contourArea, reverse=True)
            for c in cnts[:3]:
                peri = cv2.arcLength(c, True)
                approx = cv2.approxPolyDP(c, 0.05 * peri, True)
                
                if len(approx) == 4:
                    best_contour = approx
                    break
                    
        if best_contour is not None:
            break

    # --- FLATTEN THE CARD ---
    if best_contour is not None:
        log("OK", f"Found 4 corners successfully! Flattening...")
        
        pts = best_contour.reshape(4, 2) * ratio
        ordered_pts = order_points(pts)

        maxWidth = 630
        maxHeight = 880
        
        dst = np.array([
            [0, 0],
            [maxWidth - 1, 0],
            [maxWidth - 1, maxHeight - 1],
            [0, maxHeight - 1]
        ], dtype="float32")
        
        M = cv2.getPerspectiveTransform(ordered_pts, dst)
        card = cv2.warpPerspective(orig, M, (maxWidth, maxHeight))
    else:
        log("ERROR", "Extraction failed.")

    if DEBUG:
        base_filepath, _ = os.path.splitext(image_path)
        if card is not None:
            flat_file = f"{base_filepath}_flat.jpg"
            cv2.imwrite(flat_file, card)
            
        cv2.imwrite(f"{base_filepath}_debug_edges.jpg", edges)
        cv2.imwrite(f"{base_filepath}_debug_thresh.jpg", gray)

    return card

def extract_card_name(flat_card_img, image_path):
    """
    Extracts the card name from the top crop of the image using OCR and post-processing.
    
    Args:
        flat_card_img (numpy.ndarray): The flattened card image generated by OpenCV.
        image_path (str): The file path to the original image (used for debug saving).
        
    Returns:
        str: The cleaned, OCR-extracted name of the card.
    """
    log("INFO", "Extracting Card Name...")
    gray_card = cv2.cvtColor(flat_card_img, cv2.COLOR_BGR2GRAY)
    top_crop = gray_card[40:80, 48:550]

    def enhance_for_name(img, mode="black_text"):
        enhanced = cv2.resize(img, None, fx=3, fy=3, interpolation=cv2.INTER_CUBIC)
        blurred = cv2.GaussianBlur(enhanced, (5, 5), 0)
        
        if mode == "black_text":
            return cv2.adaptiveThreshold(
                blurred, 255, 
                cv2.ADAPTIVE_THRESH_GAUSSIAN_C, 
                cv2.THRESH_BINARY, 
                61, 15
            )
        elif mode == "white_text":
            _, thresh = cv2.threshold(blurred, 160, 255, cv2.THRESH_BINARY)
            final_img = cv2.bitwise_not(thresh)
            kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
            return cv2.erode(final_img, kernel, iterations=1)

    # Black text
    top_crop_black = enhance_for_name(top_crop, mode="black_text")
    raw_name = pytesseract.image_to_string(
        top_crop_black, 
        lang='eng+fra', 
        config='--psm 7'
    ).strip()

    def clean_raw_name(raw_name):
        # --- Advanced Post-Processing ---
        valid_singles = {'a', 'i', 'y', 'à', 'ô'}
        cleaned_words = []
        
        # --- FIX 3: Nuke a specific list of bad symbols ---
        bad_symbols = ['{', '}', '[', ']', '(', ')', '|', '~', '_', '\\', '/', '©']
        
        for symbol in bad_symbols:
            raw_name = raw_name.replace(symbol, '')
            
        for word in raw_name.split():
            # Check the actual alphabetical content of the word (ignores punctuation)
            alpha_only = re.sub(r'[^a-zA-Zàâäéèêëîïôöùûüÿç]', '', word)
            
            # Drop standalone punctuation (like a lone comma or hyphen)
            if len(alpha_only) == 0:
                continue
                
            # Filter single letters
            if len(alpha_only) == 1:
                # if alpha_only.lower() in valid_singles:
                if alpha_only in valid_singles:
                    cleaned_words.append(word)
                    
            # Filter multi-letter words
            else:
                # If a 2-letter word is ALL CAPS, it's a mana symbol hallucination (e.g., "VE", "RR")
                # ignore also 1-letter word ALL CAPS
                if len(alpha_only) <= 2 and alpha_only.isupper():
                    continue
                    
                cleaned_words.append(word)

        # Re-assemble the name and strip any punctuation 
        raw_name = " ".join(cleaned_words)
        raw_name = raw_name.strip(" ,.-'")
        return raw_name
    
    raw_name = clean_raw_name(raw_name)

    if raw_name.isalnum():
        log("INFO", "Pass 1 (Black Text) failed. Attempting Pass 2 (White Text)...")
        # Black text extract failed, go to white text mode
        top_crop_white = enhance_for_name(top_crop, mode="white_text")
        raw_name = pytesseract.image_to_string(top_crop_white, lang='eng+fra+jpn', config='--psm 7').strip()
        raw_name = clean_raw_name(raw_name)
        if DEBUG:
            base_filepath, _ = os.path.splitext(image_path)
            cv2.imwrite(f"{base_filepath}_white_top.jpg", top_crop_white)
    else:
        if DEBUG:
            base_filepath, _ = os.path.splitext(image_path)
            cv2.imwrite(f"{base_filepath}_black_top.jpg", top_crop_black)

    return raw_name

def extract_text_from_image(image_path):
    """
    Wrapper function to extract the flattened card image and the card name.
    
    Args:
        image_path (str): The file path to the local webcam photo.
        
    Returns:
        tuple (str | None, numpy.ndarray | None): 
        Returns (raw_name, flat_card_img).
    """
    log("INFO", f"Scanning image: {image_path}")
    
    if not os.path.exists(image_path):
        log("ERROR", f"File not found: {image_path}")
        return None, None, None, None
    flat_card_img = extract_card_from_background(image_path)
    
    if flat_card_img is None:
        return None, None, None, None

    raw_name = extract_card_name(flat_card_img, image_path)

    log("RAW", f"   -> Final OCR Name: '{raw_name}'")

    return raw_name, flat_card_img

def image_match_score(local_img, scryfall_image_url):
    """
    Compares the flattened local photo with the official Scryfall art using ORB feature matching.
    
    Args:
        local_img (numpy.ndarray): The flattened local card image.
        scryfall_image_url (str): The URL of the official artwork to download and compare against.
        
    Returns:
        int: The total number of "good" feature matches detected. A higher score means a better match.
    """
    try:

        resp = requests.get(scryfall_image_url)
        img_array = np.asarray(bytearray(resp.content), dtype=np.uint8)
        scryfall_img = cv2.imdecode(img_array, cv2.IMREAD_COLOR)

        local_img_resized = cv2.resize(local_img, (315, 440))
        scryfall_img_resized = cv2.resize(scryfall_img, (315, 440))

        gray_local = cv2.cvtColor(local_img_resized, cv2.COLOR_BGR2GRAY)
        gray_scry = cv2.cvtColor(scryfall_img_resized, cv2.COLOR_BGR2GRAY)

        orb = cv2.ORB_create(nfeatures=500)

        kp1, des1 = orb.detectAndCompute(gray_local, None)
        kp2, des2 = orb.detectAndCompute(gray_scry, None)

        if des1 is None or des2 is None:
            return 0

        bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)
        matches = bf.match(des1, des2)

        good_matches = [m for m in matches if m.distance < 50]
        
        return len(good_matches)

    except Exception as e:
        log("ERROR", f"Failed to compare images: {e}")
        return 0

def get_clean_mkm_url(card_obj):
    """
    Extracts and cleans the Cardmarket URL from the Scryfall API response. 
    If Scryfall provides a generic search link (common for non-English cards), 
    it fetches the English version to find the direct product link.
    
    Args:
        card_obj (dict): The JSON dictionary of the card returned by the Scryfall API.
        
    Returns:
        str | None: The clean, direct Cardmarket URL without affiliate tracking parameters. 
                    Returns None if no direct link exists.
    """
    raw_url = card_obj.get('purchase_uris', {}).get('cardmarket', '')

    if "Products/Search" in raw_url:
        set_code = card_obj.get('set')
        cn = card_obj.get('collector_number')
        log("INFO", "Fetching English version for precise MKM URL...")

        try:
            eng_url = f"https://api.scryfall.com/cards/{set_code}/{cn}/en"
            eng_res = requests.get(eng_url)
            time.sleep(random.uniform(0.5, 1.0))

            if eng_res.status_code == 200:
                eng_card = eng_res.json()
                raw_url = eng_card.get('purchase_uris', {}).get('cardmarket', '')
                
        except Exception as e:
            log("ERROR", f"Failed to fetch English fallback URL: {e}")

    clean_url = raw_url.split('&')[0] if raw_url else None

    if clean_url and "Products/Search" in clean_url:
        log("ERROR", "Scryfall only has a search link for this card, not a direct product link.")
        return None

    return clean_url

def verify_with_scryfall(raw_name, flattened_card):
    """
    Cross-references OCR data with the Scryfall API and visually verifies the artwork.
    
    Args:
        raw_name (str): The OCR-extracted name of the card.
        flattened_card (numpy.ndarray): The flattened local card image for visual matching.
        
    Returns:
        tuple (str | None, str | None, str | None, str | None): Returns the official (card_name, set_name, card language, clean_mkm_url).
                                                    Returns (None, None, None) if validation fails.
    """ 
    if raw_name:
        log("INFO", f"Searching for all printings of '{raw_name}' to visually match the expansion...")
        
        lang_query = " OR ".join([f"lang:{lang}" for lang in LANGUAGES])
        safe_name = raw_name.replace('"', '').replace("'", "")
        query = f'!"{safe_name}" include:extras unique:prints ({lang_query})'
        url = f"https://api.scryfall.com/cards/search?q={query}"

        try:
            res = requests.get(url)
            time.sleep(random.uniform(0.5, 1.5))
            
            if res.status_code == 200:
                cards = res.json().get('data', [])
                log("INFO", f"Found {len(cards)} different printings for {safe_name}. Testing images...")

                best_match_score = 0
                best_match_card = None

                for card in cards:
                    if 'image_uris' not in card:
                        continue 
                    
                    scry_url = card['image_uris']['normal']
                    score = image_match_score(flattened_card, scry_url)
                    
                    if score > best_match_score:
                        best_match_score = score
                        best_match_card = card

                    # Randomize the loop pause slightly (0.3 to 0.8 seconds)
                    time.sleep(random.uniform(0.3, 0.8)) 

                if best_match_card and best_match_score > MATCH_THRESHOLD:
                    log("OK", f"Match Found! Set '{best_match_card.get('set_name')}' passed with a score of {best_match_score}.")
                    return best_match_card.get('name'), best_match_card.get('set'), best_match_card.get('lang'), get_clean_mkm_url(best_match_card)
                
                log("ERROR", "Visual match failed across all printings. The OCR name might be totally wrong.")
                return None, None, None, None
                    
            else:
                log("ERROR", "Scryfall couldn't find any cards with that OCR name.")
        except Exception as e:
            log("ERROR", f"API Error: {e}")

    log("ERROR", "No Card name, nor Set to search.")
    return None, None, None, None